# Required Settings
site_url: example.com # {string}
config_path: limber # {string} path from project root to content-type config files
status: published # {select} published | private | staging (default = published)
# Optional Settings
groups: # Used to group related content-types in the UI
- label: Pages # Display name for the UI
  description: All 'articles' from content-types in the 'Pages' group
- label: Blog Posts
- label: Podcasts
  description: All 'articles' from content-types in the 'podcasts' group
- label: Globals
  description: Reusable sections of content. Like 'site-footer', 'header', 'nav', etc.
